CC = gcc
CFLAGS = -Wall -Wextra -O2

.PHONY: all clean

all: part1 part2

part1: part1.c
	$(CC) $(CFLAGS) -o part1 part1.c

part2: part2.c
	$(CC) $(CFLAGS) -o part2 part2.c

clean:
	rm -f part1 part2

